### ISSUE TITLE
2.0 Release Checklist

### ISSUE THREAD

**Issue by tylerflex** [flexcompute-readthedocs/tidy3d-docs#131]
Things we need to do before the major release. Feel free to add more.

- [ ] Ensure all links work.
- [ ] Ensure all notebook material is up to date.
- [ ] Add FAQ topics from tidy3d issues.
